name: 接收意向同意書 & 存檔

on:
  repository_dispatch:
    types: [submit_agreement]

jobs:
  save_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 建立存檔目錄
        run: mkdir -p forms

      - name: 存下 PDF（解 base64）
        env:
          PDF_B64: ${{ github.event.client_payload.pdfData }}
          NAME: ${{ github.event.client_payload.name }}
        run: |
          if [ -z "$PDF_B64" ]; then
            echo "pdfData 空值，跳過"
            exit 1
          fi

          # 防止檔名特殊字元
          SAFE_NAME=$(echo "$NAME" | sed 's/[^a-zA-Z0-9_一-龥]/_/g')
          PDF_PATH="forms/${SAFE_NAME}_同意書.pdf"

          # 移除 Data URI 前綴
          B64=$(echo "$PDF_B64" | sed 's/^data:application\/pdf;base64,//')
          echo "$B64" | base64 -d > "$PDF_PATH"

          # 確認是否成功
          if [ ! -s "$PDF_PATH" ]; then
            echo "PDF 檔案寫入失敗！"
            exit 1
          fi

      - name: 提交到 repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add forms/
          git commit -m "新增 ${{ github.event.client_payload.name }}_同意書.pdf" || echo "無變更可 commit"
          git push
