name: 接收意向同意書 & 存檔寄信

on:
  repository_dispatch:
    types: [submit_agreement]

permissions:
  contents: write

jobs:
  save_and_mail_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 建立存檔目錄
        run: mkdir -p forms

      - name: 存下 PDF（解 base64）
        env:
          PDF_B64: ${{ github.event.client_payload.pdfData }}
          NAME: ${{ github.event.client_payload.name }}
        run: |
          if [ -z "$PDF_B64" ]; then
            echo "pdfData 空值，跳過"
            exit 1
          fi

          # 檔名安全處理
          SAFE_NAME=$(echo "$NAME" | sed 's/[^a-zA-Z0-9_一-龥]/_/g')
          PDF_PATH="forms/${SAFE_NAME}_同意書.pdf"
          B64=$(echo "$PDF_B64" | sed 's/^data:application\/pdf;base64,//')
          echo "$B64" | base64 -d > "$PDF_PATH"
          if [ ! -s "$PDF_PATH" ]; then
            echo "PDF 檔案寫入失敗！"
            exit 1
          fi

      - name: 寄出 PDF 同意書郵件
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "[自動通知] 新消防特考班區隊長意向同意書"
          to: sorryxx18@gmail.com   # <-- 改成你的收件信箱
          from: "消防表單自動通知 <sorryxx18@gmail.com>"
          body: |
            您好，已收到新的消防特考班區隊長意向同意書。
            詳細資訊請見附檔。
          attachments: forms/${{ github.event.client_payload.name }}_同意書.pdf

      - name: 提交到 repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add forms/
          git commit -m "新增 ${{ github.event.client_payload.name }}_同意書.pdf" || echo "無變更可 commit"
          git push